src/cryptoadvance/specter/services/__init__.py
from ..specter_error import SpecterError


class ExtensionException(SpecterError):
    pass

src/cryptoadvance/specter/services/controller.py
import logging
from functools import wraps

from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, url_for
from flask_babel import lazy_gettext as _
from flask_login import current_user, login_required

from ..server_endpoints import flash
from ..services import ExtensionException

logger = logging.getLogger(__name__)


# This endpoint is just there to share templates between services.
services_endpoint = Blueprint(
    "services_endpoint", __name__, template_folder="templates"
)

# All blueprint from Services are no longer loaded statically but dynamically when the service-class in initialized
# check cryptoadvance.specter.services.service_manager.Service for doing that and
# check cryptoadvance.specter.services/**/manifest for instances of Service-classes and
# check cryptoadvance.specter.services.service_manager.ExtensionManager.services for initialisation of ServiceClasses


def user_secret_decrypted_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if app.config["LOGIN_DISABLED"]:
            # No logins means no password so no user_secret is possible
            flash(
                _(
                    "Service integration requires an authentication method that includes a password"
                )
            )
            return redirect(url_for(f"settings_endpoint.auth"))
        elif not current_user.is_user_secret_decrypted:
            flash(_("Must login again to enable protected Services-related data"))
            # Force re-login; automatically redirects back to calling page
            return app.login_manager.unauthorized()
        else:
            return func(*args, **kwargs)

    return wrapper


@services_endpoint.route("/choose", methods=["GET"])
def choose():
    return render_template(
        "services/choose.jinja",
        is_login_disabled=app.config["LOGIN_DISABLED"],
        specter=app.specter,
        services=app.specter.service_manager.services_sorted,
    )


@services_endpoint.route(
    "/associate_addr/<wallet_alias>/<address>", methods=["GET", "POST"]
)
@login_required
@user_secret_decrypted_required
def associate_addr(wallet_alias, address):
    wallet = app.specter.wallet_manager.get_by_alias(wallet_alias)

    if request.method == "POST":
        service_id = request.form["service_id"]
        wallet = app.specter.wallet_manager.get_by_alias(wallet_alias)
        service_cls = app.specter.service_manager.get_service(service_id)
        service_cls.reserve_address(wallet=wallet, address=address)
        return redirect(
            url_for("wallets_endpoint.addresses", wallet_alias=wallet_alias)
        )

    addr_obj = wallet.get_address_obj(address=address)

    # Inject the User's active Services
    services = []
    for service_id in current_user.services:
        try:
            services.append(app.specter.service_manager.get_service(service_id))
        except ExtensionException:
            pass

    return render_template(
        "services/associate_addr.jinja",
        specter=app.specter,
        services=services,
        wallet=wallet,
        addr_obj=addr_obj,
    )

src/cryptoadvance/specter/templates/services/choose.jinja
{% extends "base.jinja" %}

{% block head %}
<style>
    /* copied (and adapted for card-use) from here:
    * "Fork me on GitHub" CSS ribbon v0.2.3 | MIT License
    * https://github.com/simonwhitaker/github-fork-ribbon-css
    */

    .github-fork-ribbon {
        width: 12.1em;
        height: 12.1em;
        position: relative;
        overflow: hidden;
        top: -0;
        right: 0;
        z-index: 1;
        pointer-events: none;
        font-size: 10px;
        text-decoration: none;
        text-indent: -999999px;
    } 
    
    .github-fork-ribbon.fixed {
        position: fixed;
    }
    
    .github-fork-ribbon:hover, .github-fork-ribbon:active {
        background-color: rgba(0, 0, 0, 0.0);
    }
    
    .github-fork-ribbon:before, .github-fork-ribbon:after {
        /* The right and left classes determine the side we attach our banner to */
        position: absolute;
        display: block;
        width: 15.38em;
        height: 1.54em;
    
        top: -6.23em;
        right: -16.23em;
    
        -webkit-box-sizing: content-box;
        -moz-box-sizing: content-box;
        box-sizing: content-box;
    
        -webkit-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -o-transform: rotate(45deg);
        transform: rotate(45deg);
    }
    
    .github-fork-ribbon:before {
        content: "";
    
        /* Add a bit of padding to give some substance outside the "stitching" */
        padding: .38em 0;
    
        /* Set the base colour */
        background-color: #a00;
    
        /* Set a gradient: transparent black at the top to almost-transparent black at the bottom */
        background-image: -webkit-gradient(linear, left top, left bottom, from(rgba(0, 0, 0, 0)), to(rgba(0, 0, 0, 0.15)));
        background-image: -webkit-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));
        background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));
        background-image: -ms-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));
        background-image: -o-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));
        background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.15));
    
        /* Add a drop shadow */
        -webkit-box-shadow: 0 .15em .23em 0 rgba(0, 0, 0, 0.5);
        -moz-box-shadow: 0 .15em .23em 0 rgba(0, 0, 0, 0.5);
        box-shadow: 0 .15em .23em 0 rgba(0, 0, 0, 0.5);
    
        pointer-events: auto;
    }
    
    .github-fork-ribbon:after {
        /* Set the text from the data-ribbon attribute */
        content: attr(data-ribbon);
    
        /* Set the text properties */
        color: #fff;
        font: 700 1em "Helvetica Neue", Helvetica, Arial, sans-serif;
        line-height: 1.54em;
        text-decoration: none;
        text-shadow: 0 -.08em rgba(0, 0, 0, 0.5);
        text-align: center;
        text-indent: 0;
    
        /* Set the layout properties */
        padding: .15em 0;
        margin: .15em 0;
    
        /* Add "stitching" effect */
        border-width: .08em 0;
        border-style: dotted;
        border-color: #fff;
        border-color: rgba(255, 255, 255, 0.7);
    }
    
    .github-fork-ribbon.left-top, .github-fork-ribbon.left-bottom {
        right: auto;
        left: 0;
    }
    
    .github-fork-ribbon.left-bottom, .github-fork-ribbon.right-bottom {
        top: auto;
        bottom: 0;
    }
    
    .github-fork-ribbon.left-top:before, .github-fork-ribbon.left-top:after, .github-fork-ribbon.left-bottom:before, .github-fork-ribbon.left-bottom:after {
        right: auto;
        left: -3.23em;
    }
    
    .github-fork-ribbon.left-bottom:before, .github-fork-ribbon.left-bottom:after, .github-fork-ribbon.right-bottom:before, .github-fork-ribbon.right-bottom:after {
        top: auto;
        bottom: 3.23em;
    }
    
    .github-fork-ribbon.left-top:before, .github-fork-ribbon.left-top:after, .github-fork-ribbon.right-bottom:before, .github-fork-ribbon.right-bottom:after {
        -webkit-transform: rotate(-45deg);
        -moz-transform: rotate(-45deg);
        -ms-transform: rotate(-45deg);
        -o-transform: rotate(-45deg);
        transform: rotate(-45deg);
    }

</style>

{% endblock %}

{% block main %}

{% from 'services/components/plugin_card.jinja' import plugin_card %}
<div style="display: none;"><!--<style>-->

        .plugin_container {
            border: 4px solid var(--cmap-border);
            border-radius: 0.5em;
            display: inline-block;
            vertical-align: middle;
            background-color: var(--cmap-bg-lighter);
            width: 16em;
            height: 13em;
            cursor: pointer;
            padding: 1em;
            margin: 0.75em;
        }
        .plugin_container:hover {
            background-color: var(--cmap-bg-lightest);
            border: 4px solid var(--main-color);
        }

        .inner-border {
            position: relative;
            display: inline-block;
            margin: 15px;
        }
        .inner-border:before {
            border: 20px solid #192432;
            z-index: 3;
            padding: 10px;
            content: "";
            position: absolute;
            top: -25px;
            bottom: -25px;
            left: -25px;
            right: -25px;
        }

        .plugin_name {
            font-size: 1.5em;
        }
        .plugin_description {
            color: #ccc;
        }


        .endnote {
            margin-top: 4em;
        }
    </div><!--</style>-->
    <h1>{{ _("Plugins") }}</h1>
    {% if is_login_disabled %}
        <div class="yellow_warn_box">
            <p>{{ _("Current Authentication method: \"None\"")}}</p>
            <p>{{ _("Service integrations require secure per-user storage. This is only possible with a user authentication method that is password protected (any method other than \"None\").") }}</p>
            <br/>
            <p>{{ _("Select a new method in: ") }}
            <a class="btn inline-flex" href="{{ url_for('settings_endpoint.auth', next=url_for('services_endpoint.choose')) }}">{{ _("Settings") }}</a></p>
        </div>
    {% endif %}

    <div class="card center auto-width" data-style="min-width: 90%;">
        <h3 class="mt-8 mb-3">Plugins in Production</h3>
        <div class="grid grid-cols-2 gap-3">
            {% for plugin in services %}
                {% if plugin.__class__.devstatus == "prod" %}
                    {{ plugin_card(plugin.name, plugin.desc, url_for(plugin.id + '_endpoint' + '.static', filename=plugin.icon), url_for(plugin.id + '_endpoint' + '.index')) }}
                {% endif %}
            {% endfor %}
        </div>

        <h3 class="mt-8 mb-3">Plugins in Beta</h3>
        <div class="grid grid-cols-2 gap-3">
            {% for plugin in services %}
                {% if plugin.__class__.devstatus == "beta" %}
                    {{ plugin_card(plugin.name, plugin.desc, url_for(plugin.id + '_endpoint' + '.static', filename=plugin.icon), url_for(plugin.id + '_endpoint' + '.index')) }}
                {% endif %}
            {% endfor %}
            {{ plugin_card('Slush Pool', 'Import your mining rewards history', "https://github.com/kdmukai/slushpool-importer/raw/fc62445d9e1ac304cb7f0bc25ede9618bd9403dc/src/kdmukai/specterext/slushpool/static/slushpool/img/slushpool_icon.png", "https://github.com/kdmukai/slushpool-importer") }}
        </div>

        <h3 class="mt-8 mb-3">Plugins in Alpha</h3>
        <div class="grid grid-cols-2 gap-3">
            {% for plugin in services %}
                {% if plugin.__class__.devstatus == "alpha" %}
                    {{ plugin_card(plugin.name, plugin.desc, url_for(plugin.id + '_endpoint' + '.static', filename=plugin.icon), url_for(plugin.id + '_endpoint' + '.index')) }}
                {% endif %}
            {% endfor %}
            {{ plugin_card("Specter Dice", "Simulate Satoshi Dice on Regtest", "https://github.com/k9ert/specterext-dice/raw/v0.0.0-pre1/src/k9ert/specterext/dice/static/dice/dice_logo.png","https://github.com/k9ert/specterext-dice") }}
            {{ plugin_card('Spotbit', 'Price info service', "https://github.com/ahv15/spotbit/raw/spotbit-plugin/images/logos/spotbit_avatar.jpg", "https://github.com/ahv15/spotbit") }}
            {{ plugin_card('Warden', 'Portfolio tracker', "https://github.com/yogendra-17/specterext-warden/raw/20e834e32a533fd0693244efe3b2830a4cd1b79f/src/yogendra/specterext/warden/static/images/warden_square_logo.png", "https://github.com/yogendra-17/specterext-warden") }}
        </div>

        <h3 class="mt-8 mb-3">Plugin Wishlist</h3>
        <div class="grid grid-cols-2 gap-3">
            {% include "services/components/wishlist.jinja" %}
        </div>

        <div class="mt-8">
            {{ _("Some plugins might not respect the Tor-only policy.") }}
        </div>
    </div>
{% endblock %}

src/cryptoadvance/specter/templates/services/inject_in_basejinja_body_bottom.jinja
{% for _,service in specter.service_manager.services.items() %}
    {% if service.id in current_user.services %}
        {% set html_inject_in_basejinja = service.inject_in_basejinja_body_bottom() %}
        {% if html_inject_in_basejinja %}
            {{ html_inject_in_basejinja | safe }}
        {% endif %}
    {% endif %}
{% endfor %}

src/cryptoadvance/specter/templates/services/inject_in_basejinja_body_top.jinja
{% for _,service in specter.service_manager.services.items() %}
    {% if service.id in current_user.services %}
        {% set html_inject_in_basejinja = service.inject_in_basejinja_body_top() %}
        {% if html_inject_in_basejinja %}
            {{ html_inject_in_basejinja | safe }}
        {% endif %}
    {% endif %}
{% endfor %}

src/cryptoadvance/specter/templates/services/inject_in_basejinja_head.jinja
{% for _,service in specter.service_manager.services.items() %}
    {% if service.id in current_user.services %}
        {% set html_inject_in_basejinja = service.inject_in_basejinja_head() %}
        {% if html_inject_in_basejinja %}
            {{ html_inject_in_basejinja | safe }}
        {% endif %}
    {% endif %}
{% endfor %}