src/cryptoadvance/specter/services/controller.py
import logging
from functools import wraps

from flask import Blueprint
from flask import current_app as app
from flask import redirect, render_template, request, url_for
from flask_babel import lazy_gettext as _
from flask_login import current_user, login_required

from ..server_endpoints import flash
from ..services import ExtensionException

logger = logging.getLogger(__name__)


# This endpoint is just there to share templates between services.
services_endpoint = Blueprint(
    "services_endpoint", __name__, template_folder="templates"
)

# All blueprint from Services are no longer loaded statically but dynamically when the service-class in initialized
# check cryptoadvance.specter.services.service_manager.Service for doing that and
# check cryptoadvance.specter.services/**/manifest for instances of Service-classes and
# check cryptoadvance.specter.services.service_manager.ExtensionManager.services for initialisation of ServiceClasses


def user_secret_decrypted_required(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if app.config["LOGIN_DISABLED"]:
            # No logins means no password so no user_secret is possible
            flash(
                _(
                    "Service integration requires an authentication method that includes a password"
                )
            )
            return redirect(url_for(f"settings_endpoint.auth"))
        elif not current_user.is_user_secret_decrypted:
            flash(_("Must login again to enable protected Services-related data"))
            # Force re-login; automatically redirects back to calling page
            return app.login_manager.unauthorized()
        else:
            return func(*args, **kwargs)

    return wrapper


@services_endpoint.route("/choose", methods=["GET"])
def choose():
    return render_template(
        "services/choose.jinja",
        is_login_disabled=app.config["LOGIN_DISABLED"],
        specter=app.specter,
        services=app.specter.service_manager.services_sorted,
    )


@services_endpoint.route(
    "/associate_addr/<wallet_alias>/<address>", methods=["GET", "POST"]
)
@login_required
@user_secret_decrypted_required
def associate_addr(wallet_alias, address):
    wallet = app.specter.wallet_manager.get_by_alias(wallet_alias)

    if request.method == "POST":
        service_id = request.form["service_id"]
        wallet = app.specter.wallet_manager.get_by_alias(wallet_alias)
        service_cls = app.specter.service_manager.get_service(service_id)
        service_cls.reserve_address(wallet=wallet, address=address)
        return redirect(
            url_for("wallets_endpoint.addresses", wallet_alias=wallet_alias)
        )

    addr_obj = wallet.get_address_obj(address=address)

    # Inject the User's active Services
    services = []
    for service_id in current_user.services:
        try:
            services.append(app.specter.service_manager.get_service(service_id))
        except ExtensionException:
            pass

    return render_template(
        "services/associate_addr.jinja",
        specter=app.specter,
        services=services,
        wallet=wallet,
        addr_obj=addr_obj,
    )

src/cryptoadvance/specter/templates/includes/address-data.html
<template id="address-data">
	  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='output.css') }}">

    <style>
        .address-data-table td {
            text-align: left;
            margin-top: 0;
        }
        .descriptor {
            max-width: 500px;
            white-space: -moz-pre-wrap;
            white-space: -o-pre-wrap;
            white-space: pre-wrap;
            word-wrap: break-word;
        }
    </style>
    <div class="address-data bg-dark-800 rounded-xl p-4">
        <div class="flex justify-between mb-2">
            <h3 class="mb-0">{{ _("Address Data") }}</h3>
            <p class="m-0 cursor-pointer" onclick="hidePageOverlay()" class="cursor-pointer" data-cy="address-data-screen-close-btn">Close</p>
        </div>
        <div id="address-data-info" class="flex flex-col items-center"></div>
        <div class="note"></div>
    </div>
</template>
  
<script type="text/javascript">
    class AddressDataElement extends HTMLElement {
        constructor() {
            super();
            // Create a shadow root
            var shadow = this.attachShadow({mode: 'open'});
            var style = document.getElementById('address-data').content;
            var clone = style.cloneNode(true);

            this.el = clone.querySelector(".address-data");
            this.note = clone.querySelector(".note");
            this.info = clone.getElementById("address-data-info");
            this.popupContent = document.querySelector('#page_overlay_popup_content')
            this.popupContent.style.justifySelf = "start";
            this.popupContent.parentElement.style.display = "flex";

            // Read input "data-*" attributes
            this.isVerifyQR = this.getAttribute('data-verify-qr') == 'True';
            this.isVerifyHwi = this.getAttribute('data-verify-hwi') == 'True';
            this.used = (this.getAttribute('data-used') == 'true');
            this.utxo = this.getAttribute('data-utxo');
            this.amount = this.getAttribute('data-amount');
            this.amountPrice = this.getAttribute('data-amount-price');
            this.address = this.getAttribute('data-address');
            this.label = this.getAttribute('data-label');
            this.serviceId = this.getAttribute('data-service-id');
            this.wallet = this.getAttribute('data-address-wallet');

            this.note.innerText = `{{ _("Loading address") }}: ${this.address} {{ _("details") }}...`;
            this.fetchAddressData();
        
            // Attach the created element to the shadow dom
            shadow.appendChild(clone);
        }

        async fetchAddressData() {
            let url = `{{ url_for('wallets_endpoint_api.addressinfo', wallet_alias='WALLET_ALIAS') }}`.replace("WALLET_ALIAS", this.wallet);
            var formData = new FormData();
            formData.append('address', this.address);
            const jsonResponse = await send_request(url, 'POST', "{{ csrf_token() }}", formData);
            if (jsonResponse.success) {
                let descriptor = jsonResponse.descriptor;
                let xpubs_descriptor = jsonResponse.xpubs_descriptor;
                let derivation_path = jsonResponse.derivation_path;
                let addressIndex = jsonResponse.index;
                let isChange = jsonResponse.change;
                let walletName = jsonResponse.wallet_name;
                let address = jsonResponse.address;
                let walletLink = `{{ url_for('wallets_endpoint.wallet', wallet_alias='WALLET_ALIAS') }}`.replace("WALLET_ALIAS", this.wallet);
                let addressInfoHTML = `
                    <qr-code style="margin: auto;" value="bitcoin:${address}" width="256"></qr-code>
                    <table class="address-data-table -mx-4 mt-8">
                    <tbody>
                    <tr><td>{{ _("Address") }}:</td><td class="cursor-pointer" title="Copy address" style="word-break: break-all;"><explorer-link data-type="address" data-value="${address}"></explorer-link></td></tr>
                    <tr><td>{{ _("Label") }}:</td><td class="flex items-center"><address-label data-copy-hidden="true" data-address="${address}" data-wallet="${this.wallet}" data-label="${this.label}" data-service-id="${this.serviceId}"></address-label><br></td></tr>
                    <tr><td>{{ _("From wallet") }}:</td><td><a href=${walletLink}>${walletName}<a></td></tr>
                    <tr><td>{{ _("Address index") }}:</td><td>${addressIndex}</td></tr>
                    <tr><td>{{ _("Is change address") }}:</td><td>${isChange ? '{{ _("Yes") }}' : '{{ _("No") }}'}</td></tr>
                    <tr><td>{{ _("Used") }}:</td><td>${this.used ? 'Yes' : 'No'}</td></tr>
                    <tr><td>{{ _("UTXO count") }}:</td><td>${this.utxo}</td></tr>
                    <tr><td>{{ _("Amount") }}:</td><td>${this.amount} <span class="amount-price note ${this.amountPrice ? '' : 'hidden'}">${this.amountPrice}</span></td></tr>
                `;

                if ((typeof services !== 'undefined') && (this.serviceId in services)) {
                    // `services` obj made globally available in services-data.html
                    addressInfoHTML += `<tr><td>{{ _("Service") }}:</td><td class="flex items-center"><img class="h-4 align-middle my-[2px] mr-1"" src='{{ext_url_prefix}}/${this.serviceId}/static/${services[this.serviceId].icon}'>${services[this.serviceId].name}</td></tr>`;
                } else {
                    let associateServiceUrl = `{{ url_for('services_endpoint.associate_addr', wallet_alias='WALLET_ALIAS', address='ADDRESS') }}`.replace('WALLET_ALIAS', this.wallet).replace('ADDRESS', jsonResponse.address);
                    addressInfoHTML += `<tr><td>{{ _("Service") }}:</td><td><button type="button" id="associate-btn" class="btn" onclick="location.href='${associateServiceUrl}';" data-cy="associate-address-with-service-btn">&#128229;&nbsp;{{ _("Associate with a service") }}</button></td></tr>`;
                };

                // Message signing feature restricted to singlesig wallets using a Specter DIY
                {% set device = wallet.devices[0] %}
                {% if wallet.is_singlesig and device.hwi_support or wallet.is_singlesig and device.supports_qr_message_signing %}
                let redirectUrl = `{{ url_for('devices_endpoint.device', device_alias=device.alias, origin='wallet', address='ADDRESS', derivation_path='DERIVATION_PATH') }}`.replace('ADDRESS', address).replace('DERIVATION_PATH', derivation_path);
                addressInfoHTML += `<tr><td>{{ _("Message signing") }}:</td><td>
                    <button type="button" id="msg-signing-btn" class="btn" onclick="location.href='${redirectUrl}';">
                        <div style="word-wrap: anywhere">&#128396;&nbsp;{{ _("Sign a message with your") }} {{ device.name }} {{ _("device") }}</div>
                    </button></td></tr>`;
                {% endif %}

                addressInfoHTML += `
                    </td></tr>
                    </tbody>
                    </table>
                `;

                if (this.isVerifyHwi) { 
                    addressInfoHTML += `
                    <button type="button" onclick='hidePageOverlay();displayAddressOnDevice("${address}", "${descriptor}", "${xpubs_descriptor}")' class="btn" style="min-width:200px; max-width:300px; margin: auto;">{{ _("Verify address on device") }}</button>`;
                }

                if (this.isVerifyQR) { 
                    addressInfoHTML += `
                    <p>{{ _("Or scan this QR code") }}:</p>
                    <qr-code value="bitcoin:${address}?index=${addressIndex}" width="256" scalable></qr-code>`;
                }

                addressInfoHTML += `
                <h2>{{ _("Address descriptor") }}</h2>
                <div>
                    <label class="switch mb-8 flex items-center">
                        <input type="checkbox" class="descriptor-switch" checked>
                        <span class="switch-text">{{ _("Show raw public keys") }}</span>
                    </label>
                </div>
                <pre class="descriptor"><code class="explorer-link" onclick='copyText(unescape("${escape(descriptor)}"), "{{ _("Copied address descriptor") }}")'>${descriptor}</code></pre>
                `;
                this.info.innerHTML = addressInfoHTML;
                this.note.innerText = "";

                this.info.querySelector('.descriptor-switch').onchange = (e) => {
                    if (e.target.checked) {
                        this.info.querySelector(".descriptor").innerHTML = `<code class="explorer-link" onclick='copyText(unescape("${escape(descriptor)}"), "{{ _("Copied address descriptor") }}")'>${descriptor}</code>`;
                    } else {
                        this.info.querySelector(".descriptor").innerHTML = `<code class="explorer-link" onclick='copyText(unescape("${escape(xpubs_descriptor)}"), "{{ _("Copied address descriptor") }}")'>${xpubs_descriptor}</code>`;
                    }
                }

                return;
            }
        }
    }
    customElements.define('address-data', AddressDataElement);
</script>

src/cryptoadvance/specter/templates/includes/asset-label.html
<template id="asset-label">
	  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='output.css') }}">

    <div style="display: none;"><!--<style>-->
        .asset-label-form {
            display: inline;
        }
        .label {
            word-break: break-all;
            background: none;
            color: #fff;
            font-size: 1em;
            max-width: 80%;
            outline: none;
        }
        .help{
            cursor: help;
        }
        .edit, .cancel, .update {
            background: none;
            border: none;
            padding: 0;
            margin: 0;
            width: 18px;
            cursor: pointer;
        }
        .hidden {
            display: none;
        }

        .svg-white {
            filter: invert(100%) sepia(0%) saturate(1%) hue-rotate(304deg) brightness(102%) contrast(101%);
        }
        .hover .btn.edit{
            visibility: hidden;
        }
        .hover:hover .btn.edit{
            visibility: visible;
        }
        img{
            width: 22px;
            margin-bottom:-5px;
        }
    </div><!--</style>-->
    <form class="asset-label-form">
        <input type="hidden" class="csrf-token" name="csrf_token" value="{{ csrf_token() }}"/>
        <span class="label help" autocomplete="off" spellcheck="false">Fetching asset label...</span>
        <button type="button" class="btn edit" title="Edit label"><img src="{{ url_for('static', filename='img/edit.svg') }}" class="svg-white"/></button>
        <button type="button" class="btn update hidden"><img src="{{ url_for('static', filename='img/check_thick.svg') }}" class="svg-white"/>&nbsp;</button>
        <button type="button" class="btn cancel hidden"><img src="{{ url_for('static', filename='img/cross_thick.svg') }}" class="svg-white"/></button>
    </form>
</template>

<script type="text/javascript">
    class AssetLabelElement extends HTMLElement {
        constructor() {
            super();
            // Create a shadow root
            var shadow = this.attachShadow({mode: 'open'});
            var style = document.getElementById('asset-label').content;
            var clone = style.cloneNode(true);
            this.el = clone.querySelector(".asset-label-form");
            this.label = clone.querySelector(".label");
            this.update = clone.querySelector(".update");
            this.cancel = clone.querySelector(".cancel");
            this.edit = clone.querySelector(".edit");
        
            // Attach the created element to the shadow dom
            shadow.appendChild(clone);
        }

        async connectedCallback() {
            this.asset = this.getAttribute('data-asset');
            this.labelValue = this.getAttribute('data-label');
            // edit-mode can be 'hover', 'disabled', 'enabled'
            this.mode = this.getAttribute('edit-mode');
            // we don't know the asset
            if( (this.asset == null) ||
                (this.asset == "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff") ||
                (this.asset == "0000000000000000000000000000000000000000000000000000000000000000")){
                this.asset = "Confidential";
                this.labelValue = "Confidential";
                this.mode = "disabled";
            }

            // Set the label - fetch if not specified
            if (this.labelValue) {
                this.label.innerText = this.labelValue;
            } else {
                await this.fetchAssetLabel();
            }

            if(!this.mode){
                this.mode = 'hover';
            }
            // disallow changing LBTC label
            if(this.labelValue == "LBTC" || this.labelValue == "tLBTC"){
                this.mode = 'disabled';
            }
            if(this.mode == 'disabled'){
                this.edit.classList.add('hidden');
            }else if(this.mode == 'hover'){
                this.el.classList.add('hover');
            }
            this.label.title = this.asset;
            this.isEditing = false;

            // Set title mode for asset-label element
            if (this.getAttribute('date-size') == 'title') {
                this.isTitle = true;
                this.label.style.fontSize = '1.5em';
                this.el.style.fontSize = '1.2em';
                this.edit.style.width = '30px';
                this.edit.children[0].style.width = '30px';
            } else {
                this.isTitle = false;
            }

            // Ensure text pasted is not formatted with special formatting.
            this.label.addEventListener('paste', function (event) {
                event.preventDefault();
                document.execCommand('inserttext', false, event.clipboardData.getData('text/plain'));
            });
            this.label.addEventListener("keypress", (event) => {
              // Number 13 is the "Enter" key on the keyboard
              if (event.keyCode === 13) {
                // Cancel the default action, if needed
                event.preventDefault();
                this.label.innerText = this.label.innerText.replaceAll("\n","");
                // Trigger the button element with a click
                this.update.click();
              }
            });
            this.edit.onclick = () => {
                this.label.setAttributeNode(document.createAttribute('contenteditable'));
                if (this.isTitle) {
                    this.label.style['font-size'] = '1.1em';
                }
                this.label.style['border-bottom'] = '1px solid #ccc';
                this.labelValue = this.label.innerText;
                this.edit.classList.add('hidden');
                this.label.classList.remove('help')
                this.cancel.classList.remove('hidden');
                this.update.classList.remove('hidden');
                this.isEditing = true;
                // focus
                this.label.focus();
                // select content
                let sel = window.getSelection();
                let range = document.createRange();
                range.selectNodeContents(this.label);
                sel.removeAllRanges();
                sel.addRange(range);
            }

            this.cancel.onclick = () => {
                this.label.innerText = this.labelValue;
                this.closeEditMode();
            }

            this.update.onclick = async () => {
                if (await this.setAssetLabel()) {
                    this.labelValue = this.label.innerText;
                    this.closeEditMode();
                    let event = new CustomEvent('updateAssetLabel', { detail: {
                        label: this.labelValue,
                        asset: this.asset,
                    }});
                    document.dispatchEvent(event);
                    if (!this.labelValue) {
                        this.label.innerText = this.asset
                    }
                } else {
                    showError(`{{ _("Failed to update asset label. Please refresh the page and try again.") }}`)
                }
            }
        
            document.addEventListener("updateAssetLabel", (e) => {
                if (this.asset != e.detail.asset) {
                    return
                }
                this.labelValue = e.detail.label
                if (!this.isEditing) {
                    if (e.detail.label) {
                        this.label.innerText = e.detail.label
                    } else {
                        this.label.innerText = e.detail.asset
                    }
                }
            });
        }
        
        closeEditMode() {
            this.label.removeAttribute('contenteditable')
            if (this.isTitle) {
                this.label.style['font-size'] = '1.5em';
            }
            this.label.style.border = 'none';
            this.edit.classList.remove('hidden');
            this.label.classList.add('help')
            this.cancel.classList.add('hidden');
            this.update.classList.add('hidden');
            this.isEditing = false;
        }

        async fetchAssetLabel() {
            const url = `{{ url_for('settings_endpoint.get_asset', asset="HEXID_ASSET") }}`.replaceAll('HEXID_ASSET', this.asset);
            const response = await fetch(url);
            const jsonResponse = await response.json();
            if("label" in jsonResponse){
                this.labelValue = jsonResponse.label;
                this.label.innerText = this.labelValue;
            }
            if("error" in jsonResponse){
                showError(jsonResponse.error);
            }
        }

        async setAssetLabel() {
            let url = `{{ url_for('settings_endpoint.set_asset_label') }}`;
            var formData = new FormData();
            formData.append('asset', this.asset);
            formData.append('label', this.label.innerText);
            formData.append('csrf_token', '{{ csrf_token() }}');
            try {
                const response = await fetch(
                    url,
                    {
                        method: 'POST',
                        body: formData
                    }
                );
                if(response.status != 200){
                    showError(await response.text());
                    return;
                }
                const jsonResponse = await response.json();
                return jsonResponse.success;
            } catch(e) {
                console.log("Caught error: ", e);
                showError(e);
                return false;
            }
        }
    }

    customElements.define('asset-label', AssetLabelElement);
</script>

src/cryptoadvance/specter/templates/includes/coin_selection.html
<template id="coin-selection">
	  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='output.css') }}">
    <span class="toggle_coinselection mt-3 cursor-pointer" data-cy="coin-selection-toggle">{{ _("Coin selection") }} {% if show_advanced_settings %}&#9660;{% else %}&#9654;{% endif %}</span>
    <div class="coinselection_div hidden">
        <div class="errorMessagesDiv">
            <message-box type="error" class="hidden"></message-box>
        </div>
        <tx-table
            class="txtable"
            btc-unit="{{ specter.unit }}"
            hide-sensitive-info="{{ specter.hide_sensitive_info | lower }}"
            type="utxo" hide-columns="category time txid confirmations action" 
            blockhash="true" hide-switcher="true"
            wallet="{{ wallet.alias }}"
            table-max-height="600px"
            scrollbar="on">
        </tx-table>
    </div> 
</template>


<script type="module">
    /**
     * Custom element for showing the coin-selection-dialog
       attributes:
       * wallet-alias
       * spendable-amount
       Example:
        <coin-selection  
            id="coinselection-webcomponent"
            wallet-alias="{{wallet.alias}}"
            spendable-amount='{{ wallet.amount_available | btcamount }}'
            is-liquid="{{specter.is_liquid}}"
            selected-coins="{{ selected_coins }}">
        </coin-selection>
        Internally, a tx-table is used which is customizable in order to be useful here.
        We're using the asset_balance endpoint to get Liquid assets.
     */
    class CoinSelection extends HTMLElement {
        constructor() {
            super();
            var shadow = this.attachShadow({mode: 'open'});
            var template_content = document.getElementById('coin-selection').content;
            var clone = template_content.cloneNode(true);
            
            this.coinselectionDiv = clone.querySelector(".coinselection_div")
            this.txtable = clone.querySelector(".txtable")
            this.txtable.addEventListener("CustomSelected", (event) => {
                this.updateLd();
                this.fireChangeEvent();
            } )

            // ErrorMessages
            this.errorMessagesDiv = clone.querySelector(".errorMessagesDiv");

            // toggler
            this.toggler = clone.querySelector(".toggle_coinselection")
            this.toggler.addEventListener('click', (event) => {
                this.toggleCoinselection()
			});

            this.createLighterDOMNodes()

            // Attach the created element to the shadow dom
            shadow.appendChild(clone);
        }
        /**
         * Browser calls this method when the element is added to the document
         * (can be called many times if an element is repeatedly added/removed)
        */
        connectedCallback() {
            this.walletAlias = this.getAttribute('wallet-alias');
            this.spendableAmount = this.getAttribute("spendable-amount") ?? 0
            if (this.getAttribute("is-liquid") == "True") {
                this.classList.add("hidden")
            }
            let selectedCoins = JSON.parse(this.getAttribute('selected-coins').replace(/'/g, '"'));
            if (selectedCoins.length > 0) {
                this.txtable.setAttribute("selected-coins", JSON.stringify(selectedCoins))
                // unfold if we have preselected coins
                this.toggleCoinselection()
            }
        }

        /**
         * here, we create some kind of mirror-nodes in the lighterDOM so that the outer form can 
         * pick the values up. They are all hidden and we'll clone them from their "peer" from the shadowDOM
         * Check https://stackoverflow.com/a/38667839/330964 for details
         */
        createLighterDOMNodes() {
            this.ld = {} // in order to separate clearly, we store all of them here
            // We won't mirror fee_options, that's too much overhead. We create a textfield there:
            this.ld.div = document.createElement("div");
            this.ld.div.type = "hidden";
            this.appendChild(this.ld.div);
        }

        fireChangeEvent() {
            let event = new CustomEvent('change', {});
            this.dispatchEvent(event);
        }
    
        handleError(errorText) {
            console.log(errorText)
            const messageBox = document.createElement('message-box');
            //messageBox.setType("error")
            messageBox.textContent = errorText
            this.errorMessagesDiv.appendChild(messageBox)
        }

        isCoinSelectionActive() {
            return !this.coinselectionDiv.classList.contains('hidden');
        }

        getSpendableAmount(unit) {
            let spendableAmount;
            if (!this.isCoinSelectionActive()) {
                if(unit == 'btc' || unit == 'sat'){
                    spendableAmount = '{{ wallet.amount_available }}';
                } else {        
                    if (unit in assetBalances){
                        return assetBalances[unit].balance;
                    } else {
                        return 0;
                    }
                }
            } else {
                spendableAmount = this.getCoinSelectedAmount();
            }
    
            return (unit == 'sat' ? spendableAmount * 100000000 : spendableAmount);
        }

        /**
         * Updates the lightDOM: It creates one hidden input-element for each tx which is selected in the shadowDOM
         */
        updateLd() {
            while (this.ld.div.lastChild) {
                this.ld.div.removeChild(this.ld.div.lastChild);
            }
            this.txtable.getSelectedTxs().forEach( (tx) => {
                var element = document.createElement("input");
                element.type = "hidden";
                element.name = "coinselect"
                element.classList.add("coinselect-hidden") // for cypress-tests
                element.value= tx.txid + "," + tx.vout

                this.ld.div.appendChild(element)
            })
        }

        getCoinSelectedAmount() {
            var sum = 0
            this.txtable.getSelectedTxs().forEach( (tx) => {
                sum = sum + tx.amount
            })
            sum = Number.parseFloat(sum.toFixed(8))
            return sum
        }
    
        toggleCoinselection() {
            if (!this.coinselectionDiv.classList.contains('hidden')) {
                this.coinselectionDiv.classList.add('hidden')
                this.toggler.innerHTML = `{{ _("Coin selection") }} &#9654;`
                this.removeSelection()
            } else {
                this.coinselectionDiv.classList.remove('hidden')
                this.toggler.innerHTML = `{{ _("Coin selection") }} &#9660;`
            }
        }

        removeSelection() {
            this.txtable.unselect_all()
            // We also need to update the Light DOM
            this.updateLd()
        }

        shouldSelectMoreCoins(unit, amount) {
            return (unit == 'sat' ? amount / 100000000 : amount) > this.getCoinSelectedAmount() && this.isCoinSelectionActive()
        }
    }


    customElements.define('coin-selection', CoinSelection);

    
</script>

src/cryptoadvance/specter/templates/includes/explorer-link.html
<template id="explorer-link">
	  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='output.css') }}">
    {% if specter.explorer %}
        <a class="explorer-link cursor-pointer no-underline hover:underline hover:text-white" target="_blank"></a>
    {% else %}
        <span class="explorer-link cursor-pointer no-underline hover:underline hover:text-white"></span>
    {% endif %}
</template>
  
<script type="text/javascript">
    class ExplorerLinkElement extends HTMLElement {
        constructor() {
            super();
            // Create a shadow root
            var shadow = this.attachShadow({mode: 'open'});
            var style = document.getElementById('explorer-link').content;
            var clone = style.cloneNode(true);
        
            this.explorerLink = clone.querySelector(".explorer-link");
            this.explorer = '{{specter.explorer}}'
            this.type = this.getAttribute('data-type');
            this.value = this.getAttribute('data-value');
            if (this.explorer) {
                this.explorerLink.href = `${ this.explorer }${ this.type }/${ this.value }`
            } else {
                this.explorerLink.addEventListener('click', () => {
                    copyText(this.value, `Copied ${ this.type }: ${ this.value }`);
                });
            }
            this.explorerLink.innerText = this.value;
        
            // Attach the created element to the shadow dom
            shadow.appendChild(clone);
        }
    }
    
    customElements.define('explorer-link', ExplorerLinkElement);
</script>